### ISSUE TITLE
bulds for ppc64le appear broken

### ISSUE THREAD

**Issue by beckermr** [conda-forge/scipy-feedstock#106]
It appears that the builds for ppc64le are not passing the scipy tests. See this PR and comment, https://github.com/conda-forge/scipy-feedstock/pull/105#issuecomment-514865180.

**Comment by jakirkham** [comment]
@jayfurmanek, do you have any thoughts on this one?

**Comment by jakirkham** [comment]
Linking [the build logs from `master`]( https://travis-ci.org/conda-forge/scipy-feedstock/builds/573015279 ).

**Comment by jakirkham** [comment]
This seems to be fixed with more recent builds. Closing this out.
