### ISSUE TITLE
Windows with strict channel priority breaks many dependencies.

### ISSUE THREAD

**Issue by peterdhansen** [conda-forge/scipy-feedstock#120]
Issue: cannot solve dependencies on scipy with strict dependencies. 

When I use conda forge in the way recommended  by [the documentation](https://conda-forge.org/docs/user/tipsandtricks.html), I setup my `.condarc` as shown below. 

Because of strict priority the new windows build that was uploaded #119 supersedes every version available in the `default` channel. So anything that depends on scipy and requires python < 3.8 will fail with this setup.

Is the correct answer to remove strict priority? or is there a way to force my environment to use a different channel for just scipy?

<br/>
`.condarc`
<details>
```
ssl_verify: true
channel_priority: strict
channels:
  - conda-forge
  - defaults
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : D:\Anaconda
            shell level : 1
       user config file : C:\Users\peter.hansen\.condarc
 populated config files : C:\Users\peter.hansen\.condarc
          conda version : 4.7.12
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages :
       base environment : D:\Anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\peter.hansen\.conda\pkgs
                          C:\Users\peter.hansen\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\peter.hansen\.conda\envs
                          C:\Users\peter.hansen\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by woest** [comment]
I have this problem as well. I think this happens because of https://github.com/conda-forge/scipy-feedstock/issues/119

conda-forge now has a scipy build, but it is only for python 3.8. So conda tries to solve on the conda-forge channel for python 3.8, but a significant portion of the packages does not have a python 3.8 build yet.

I think a solution would be offering a scipy windows build for 3.6 and 3.7 as well...

**Comment by rgommers** [comment]
@mariusvniekerk any thoughts? you may be the only one with the setup to add py36/py37 builds

**Comment by ocefpaf** [comment]
I can confirm this. Without builds for 3.6 and 3.7 one must re-order the channels or remove `strict` to avoid forcing python=3.8 and conflicts.

@mariusvniekerk I can do the extra builds but I would need your help/guidance to do it. If you have some extra time ping me.

**Comment by djhoese** [comment]
I'm running in to this too. Was able to get my package's CI tests passing by setting channel priority to `flexible`. Had to do it *only* for Windows as it seems rasterio was not happy on Linux (that may have been disabled channel priority though).

**Comment by djhoese** [comment]
@ocefpaf Has there been any work on this? Let me know if there is something I can do to help.

**Comment by ocefpaf** [comment]
> @ocefpaf Has there been any work on this? Let me know if there is something I can do to help.

Pinging @mariusvniekerk b/c we just spoke about this. If I can have the details on the py38 build I can do the py36 and py37 on my machine or the same VM.

**Comment by isuruf** [comment]
@ocefpaf, we could also copy the defaults packages temporarily.

**Comment by ocefpaf** [comment]
> @ocefpaf, we could also copy the defaults packages temporarily.

We thought about that but how many packages would we need to copy? mkl, numpy-base, etc. Maybe this path will bring more headaches that just building our own versions.

**Comment by isuruf** [comment]
@ocefpaf, no just `scipy` is enough. `numpy` will come from `conda-forge` and `mkl` from defaults with or without strict channel priority.

**Comment by ocefpaf** [comment]
> @ocefpaf, no just `scipy` is enough. `numpy` will come from `conda-forge` and `mkl` from defaults with or without strict channel priority.

I remember some trouble with that but I guess that your blas split some time ago will handle that. Let's give it a shot. Copying them now...

**Comment by ocefpaf** [comment]
@peterdhansen, @woest and @djhoese can you test it again and let us know if this is fixed? If not let's re-open this.

**Comment by woest** [comment]
Seems to be working for me.

**Comment by djhoese** [comment]
Works for me too. Thanks!
