### ISSUE TITLE
scipy bad build: ImportError: cannot import name '_ccallback_c'

### ISSUE THREAD

**Issue by pseudotensor** [conda-forge/scipy-feedstock#137]
https://anaconda.org/conda-forge/scipy/1.4.1/download/linux-64/scipy-1.4.1-py36h832618f_3.tar.bz2

This package is bad and leads to
```
(base) $ python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import stats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jon/minicondadai/lib/python3.6/site-packages/scipy/__init__.py", line 148, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/home/jon/minicondadai/lib/python3.6/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c'
```

However the build https://anaconda.org/conda-forge/scipy/1.4.1/download/linux-64/scipy-1.4.1-py36h2d22cac_3.tar.bz2 has no such problem. But conda chooses the latest build.

The build https://anaconda.org/conda-forge/scipy/1.4.1/download/linux-64/scipy-1.4.1-py36h832618f_3.tar.bz2 should be removed.

Question: How does conda-forge test builds? This is a basic import that should fail.

**Comment by marcelotrevisani** [comment]
ping @conda-forge/core  @conda-forge/scipy

**Comment by beckermr** [comment]
We import everything and run a significant portion of the test suite on some platforms.

https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/run_test.py

**Comment by beckermr** [comment]
This error slipping through that is pretty surprising.

**Comment by beckermr** [comment]
The test for your specific module is here: https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/run_test.py#L72

**Comment by isuruf** [comment]
@pseudotensor, please don't open issues without the information asked in the issue template.

**Comment by pseudotensor** [comment]
Perhaps the problem is that I manually chose that scipy build and expected it to work regardless of other packages.  If I ask conda to find a solution, no matter how I use that "bad" package, it changes the build for all other packages.

I'm new to conda, so I wasn't aware what the different builds are for.  I presume it's to connect to specific other packages.

So I was just misusing conda.

**Comment by isuruf** [comment]
You were trying to install the PyPy build into a CPython env, so it will not work.
