### ISSUE TITLE
Python 3.9 builds for windows

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/scipy-feedstock#139]
Merging #138 only built for linux/osx but continues the 3.9-migration. However, all packages depending on scipy and building for windows will necessarily fail without a windows build (from either CF or anaconda). Last time, this was done manually, I believe (cf. #119).

**Comment by Anthchirp** [comment]
Thanks for creating this ticket to keep track of things. I've retriggered all linked in PRs.
