### ISSUE TITLE
Addition of boost as a dependency via git submodules in scipy 1.7.dev0

### ISSUE THREAD

**Issue by rth** [conda-forge/scipy-feedstock#158]
From the discussion in https://github.com/scipy/scipy/pull/13328 it looks like this might happen.

If you have any comments from the packaging perspective, please contribute to the discussion in the linked issue.
Related : https://mail.python.org/pipermail/scipy-dev/2021-February/024524.html

**Comment by h-vetinari** [comment]
This has been done - 1.7.0 was released with that submodule, and #169 packaged it.
