### ISSUE TITLE
Proposed build system changes to SciPy

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scipy-feedstock#164]
Please see issue ( https://github.com/scipy/scipy/issues/13615 ) for details

**Comment by h-vetinari** [comment]
Here's the upstream PR: https://github.com/scipy/scipy/pull/14847

**Comment by rgommers** [comment]
This is a reminder that once we switch to Meson in this feedstock, we should remove the `setuptools<60.0` pin introduced in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/212.
