### ISSUE TITLE
scipy 0.18.1?

### ISSUE THREAD

**Issue by zym1010** [conda-forge/scipy-feedstock#18]

**Comment by jakirkham** [comment]
Please open PRs against `master` and against `v0.18_np1.10`.

**Comment by jakirkham** [comment]
Have merged PRs ( https://github.com/conda-forge/scipy-feedstock/issues/19 ) and ( https://github.com/conda-forge/scipy-feedstock/issues/20 ). All builds of SciPy 0.18.1 are released. Thanks for putting them together, @zym1010. 😄
