### ISSUE TITLE
Newer versions of SciPy using Boost

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scipy-feedstock#190]
Just leaving a note here that newer versions of SciPy will use Boost ( https://github.com/scipy/scipy/pull/13328 ). We will likely want to unvendor the version packaged in SciPy so we can use the conda-forge Boost package here.

**Comment by h-vetinari** [comment]
This has already [landed](https://github.com/conda-forge/scipy-feedstock/commit/d1eb09f45445ccc032f728ef6cad99c8a439c9e0) in #169. There was some discussion [here](https://github.com/conda-forge/scipy-feedstock/pull/169#issuecomment-855450934), with the pertinent bit being [emphasis mine]:

> > @h-vetinari: would it make sense to build this against conda-forge boost?
> 
> @rgommers: What would the advantage be? SciPy requires this exact version of Boost (1.76.0 didn't work), it may or may not be patched in the future, _**and SciPy only supports building it via that submodule**_.

**Comment by jakirkham** [comment]
Ah ok. Sorry for missing that.

For header only as long as no symbols are leaked, wouldn't expect any issues.

Some parts of Boost are not header only and ship libraries. So that's something we should keep an eye on (though presumably upstream would be thinking about this as well)

**Comment by h-vetinari** [comment]
I think there's nothing left to do here for the moment; closing.
