### ISSUE TITLE
BUG: conda install of scipy and python ot yields GLIBCXX_3.4.29 error #18163

### ISSUE THREAD

**Issue by dsm-72** [conda-forge/scipy-feedstock#230]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/scipy/scipy/issues/18163

> This would seem to be a conda packaging issue. Could you report this issue at https://github.com/conda-forge/scipy-feedstock/issues. It might be similar to https://github.com/conda-forge/scipy-feedstock/issues/211?

### Installed packages

```shell
name: test
channels:
  - defaults
  - conda-forge


dependencies:  
  - python>=3.10  
  - scipy

  # do pip last to prevent as many conflicts as possible
  - pip
  - pip:    
    - pot


conda env create -f env.yml
```

### Environment info

```shell
name: test
channels:
  - defaults
  - conda-forge


dependencies:  
  - python>=3.10  
  - scipy

  # do pip last to prevent as many conflicts as possible
  - pip
  - pip:    
    - pot


conda env create -f env.yml
```

**Comment by h-vetinari** [comment]
You have your channel order wrong (to be raising a bug against conda-forge), because it prefers `defaults` to conda-forge. If you want to use the only way conda-forge is supported, please do what every feedstock README asks:
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```

**Comment by dsm-72** [comment]
@h-vetinari how does one set that in the yaml file?

**Comment by h-vetinari** [comment]
As for `conda config --set channel_priority strict`, you'll have to do this through the CLI, or you can set that in your `$HOME/.condarc` (which is where it ends up if you do it with the CLI). At least I doubt it'd be picked up from an environment.yaml, but I haven't tried. In any case, it's reasonable even for setting this globally.

Side note, the environment files are not a replacement for the content of `conda list` and `conda info` when filing a bug report. Those contain _much_ more information.

**Comment by dsm-72** [comment]
@h-vetinari  I tried your suggestion (removed defaults, created a new env) and the issue persists

**Comment by h-vetinari** [comment]
> Side note, the environment files are not a replacement for the content of `conda list` and `conda info` when filing a bug report. Those contain _much_ more information.

In that case... ☝️

**Comment by h-vetinari** [comment]
Your environment is full of packages from other channels (defaults, pytorch), and packages from pypi - there are infinitely[^1] many ways for such setups to break, and you found one! 🥳 

You'll have to set strict channel priority as I described. Every package available in conda-forge needs to come from conda-forge, no exceptions. If that's the case and you still have issues, let us know.

[^1]: this is only a slight exaggeration; you have 257 packages in your environment from 4 different sources. Testing all different combinations of that would be... 4 ** 257 = 53631231719770388398296099992823384509917463282369573510894245774887056120294187907207497192667613710760127432745944203415015531247786279785734596024336384 combinations.

**Comment by dsm-72** [comment]
@h-vetinari I appreciate it. Ill set up a virtual box and do everything clean with strict channel priority

**Comment by h-vetinari** [comment]
Closing this one as stale. Please open a new issue if the issue can be reproduced, or let me know here and I can reopen.
