### ISSUE TITLE
`pooch` runtime dependency intended?

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/scipy-feedstock#247]
### Comment:

Hi. PR #221 made `pooch` an install dependency of `scipy`.

https://github.com/conda-forge/scipy-feedstock/blob/3a08a185e651cecdc19023d04c22677b5bdc5d26/recipe/meta.yaml#L105-L110

Was this intended? I assume no, as `pooch` is not a [formal requirement of `scipy`](https://github.com/scipy/scipy/blob/986f248024afb0dc3646d43b963dfe43d9e3cdbb/pyproject.toml#L47-L51), but maybe it was as it was added in the very first commit in PR #221.

From a downstream users view (c.f. https://github.com/conda-forge/pyhf-feedstock/issues/21) it was just very strange to see an unexpected dependency getting installed with no runtime requirement link.

```console
$ docker run --rm -ti mambaorg/micromamba:1.4.9-bullseye-slim
(base) mambauser@29855946c848:/tmp$ micromamba install --yes --channel conda-forge scipy
(base) mambauser@29855946c848:/tmp$ python -m pip show scipy | grep Req
Requires: numpy
Required-by: 
(base) mambauser@29855946c848:/tmp$ python -m pip show pooch | grep Req
Requires: packaging, platformdirs, requests
Required-by: 
(base) mambauser@29855946c848:/tmp$ 
```

cc @h-vetinari

**Comment by h-vetinari** [comment]
I mean, there's a comment right above it. It's an [optional](https://github.com/scipy/scipy/blob/v1.11.2/scipy/datasets/_utils.py#L18-L21) dependency of scipy, that we're including to have a fully functional package. We could presumably take it out an let users install it themselves if they have a need for it. I don't really mind either way. Thoughts @rgommers?

**Comment by matthewfeickert** [comment]
> It's an [optional](https://github.com/scipy/scipy/blob/v1.11.2/scipy/datasets/_utils.py#L18-L21) dependency of scipy, that we're including to have a fully functional package.

Yes, I assumed that you wouldn't be distributing optional dependencies by default.

While I appreciate that you're being selective in your scope, as conda doesn't have the concept of extras I expect that no conda-forge package distributes optional dependnecies by default. `pooch` is not that big of a deal in the grand scheme of things (though this also forces users to install additional dependencies beyond core requirements), but obviously this could explode if this became a norm. 

> We could presumably take it out an let users install it themselves if they have a need for it. I don't really mind either way.

Removing it would be great, if you as a team are okay with doing it.

**Comment by agoose77** [comment]
I would like to chime in here: for conda-forge/hist-feedstock and conda-forge/uproot-feedstock we now split into `XXX` and `XXX-base`. This has several benefits; smaller environments, better chance of working with emscripten-forge.

The latter is a big motivator for me. `matplotlib` also does this metapackage approach.

**Comment by h-vetinari** [comment]
I'm well aware of the possibility to split things into several outputs. We did this already for the tests here, but it did not seem worthwhile for pooch alone.

> Removing it would be great, if you as a team are okay with doing it.

You can open a PR that moves it from a run-dep of `scipy` to a test-dep of `scipy-tests` (+ bump the build number). If someone wants to chime in, they can do it there.

**Comment by rgommers** [comment]
Leaving out `pooch` seems reasonable; the `scipy.datasets` functionality that needs it already gives clear errors when it's missing and the user is expected to install it to resolve those.

In general, leaving optional dependencies out to keep environments small seems like the right thing to do. There may be some judgement calls involved of course.

I don't like the `-base` approach much for packages like `numpy` and `scipy`. The `defaults` channel had a `numpy-base` package, and it was pretty annoying/confusing. Here I don't see a reason for a `scipy-base`, just removing `pooch` as a dependency will do.
