### ISSUE TITLE
`scipy=1.11.4` is missing linux-aarch64 builds 

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/scipy-feedstock#260]
### Comment:

I attempted to install the latest `scipy` release on a linux-aarch64 machine, but noticed that there isn't a build for that architechture for the 1.11.4 release. Looking at previous release like 1.11.3, there are linux-aarch64 builds https://anaconda.org/conda-forge/scipy/files

**Comment by h-vetinari** [comment]
Yes, we're running into https://github.com/scipy/scipy/issues/19210. Is there a specific bugfix that you need from 1.11.4, or can you stay with 1.11.3 for now?

**Comment by h-vetinari** [comment]
While there are no builds for 1.11.4, I've now skipped the (apparently spuriously) failing on aarch, so there'll be a 1.12.0 as soon as CI runs through (and the CDN picks up the new files).
