### ISSUE TITLE
Should `scipy-tests` have a runtime dependency on `pytest`?

### ISSUE THREAD

**Issue by lucascolley** [conda-forge/scipy-feedstock#288]
What do you think @h-vetinari ? I suppose it is incorrect to say that `pytest` is a runtime dependency. But I was surprised that `scipy.test()` didn't work out of the box with `pixi add scipy-tests`. My thinking is that, if anyone is installing `scipy-tests` instead of `scipy`, they will be wanting to run the tests.

**Comment by h-vetinari** [comment]
Yeah, since `scipy-tests` is specifically for that, it'd be fine to add pytest (and other non-optional test dependencies) to the run requirements.
