### ISSUE TITLE
Dropping support for 0.17

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scipy-feedstock#46]
Opening this issue to test the waters. Was curious if people are still making using of SciPy 0.17.

If not, I'd like to consolidate the branches on this feedstock. My current thinking is we merge these old branches into newer maintained branches (potentially even `master`), but prefer the upstream branch for all changes. This allows us to keep the history from these branches while being able to delete them.

Thoughts?

cc @pelson @ocefpaf @kmuehlbauer @conda-forge/core

**Comment by kmuehlbauer** [comment]
@jakirkham 

The scipy issues we had within `wradlib` and `pytmatrix` are sorted out IIRC. At least scipy 0.18.1 was used in both project's latest builds.
