### ISSUE TITLE
CircleCI build near time limit

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/scipy-feedstock#8]
It seems the CircleCI build is near the time limit. This slowed our rebuild process today as the [build failed](https://circleci.com/gh/conda-forge/scipy-feedstock/41) once due to being over time. However, it seems all of the `0.18.0` builds are pretty close to that limit. Due we know of a way to do a parallel build for `scipy`? If so, we can try to leverage the 2 cores CircleCI gives us to speed up this build. Are there other build optimizations we could try? If we can't think of anything else, we could explore using CircleCI's parallelism feature with some changes to `conda-smithy` ( https://github.com/conda-forge/conda-smithy/issues/203 ). However, that last option might take a bit longer to come together.

**Comment by rgommers** [comment]
There's now a ``-parallel`` keyword in ``numpy.distutils``, but it was only added in numpy 1.10.0. Not twice as fast, but it should help a bit.

**Comment by jakirkham** [comment]
Nice! That is good info. Thanks @rgommers. Do we specify the number of threads to use? Are there some docs I should read up on?

Also, saw there was a `-j ` option, but I don't know if this is related. Though `-j` didn't seem to help much based on reports ( https://github.com/scipy/scipy/issues/6225 ), but maybe it helps enough.

**Comment by rgommers** [comment]
Missed this question, sorry for the slow reply @jakirkham. Yes, ``-j`` is the one-letter version of ``--parallel`` so they're the same. And yes, you do specify the number of threads with an integer. Or set this as default behavior with the ``NPY_NUM_BUILD_JOBS`` envvar. There isn't too much documentation, but this describes things: http://docs.scipy.org/doc/numpy-dev/user/building.html#parallel-builds

**Comment by jakirkham** [comment]
Just got done working up a proposal to `conda-smithy` that will allow for matrix builds on CircleCI. Expect this will improve the situation here greatly. One caveat though is it requires CircleCI 2.0, which is technically still in Beta (though has been around since late last year). That said, it seems to do ok on some basic tests. More details can be found in PR ( https://github.com/conda-forge/conda-smithy/pull/532 ).

**Comment by jakirkham** [comment]
This is not really an issue now that there are matrix builds on CircleCI and we pin NumPy differently. Given this, am closing this issue.
