### ISSUE TITLE
scipy, Windows, and openblas conflicts

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/scipy-feedstock#84]
This is probably not entirely in the right place but I didn't know where else it belonged, sorry for that.

After months of trying to get `kwant` to build for windows in https://github.com/conda-forge/kwant-feedstock/pull/42 we finally [succeeded (builds + tests passed)](https://ci.appveyor.com/project/conda-forge/kwant-feedstock/build/1.0.43/job/xekbamos0rtkmv08) about a month ago.  However, now that we are ready to release (because there is a tagged version) the [builds don't succeed](https://ci.appveyor.com/project/conda-forge/kwant-feedstock/build/1.0.46/job/3lnxwg1mfr4e294n). 

I get 
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'scipy', '*[track_features=blas_openblas]', 'blas==1.1=openblas'}
```
AFAIU that is not possible because `scipy` comes from `defaults`. @isuruf as Windows expert, do you understand why this happens?

**Comment by ocefpaf** [comment]
We need to finish #78 to fix that.

**Comment by basnijholt** [comment]
Thanks @ocepaf!

We were able to fix it by building with MKL for Windows 👍

**Comment by basnijholt** [comment]
Thanks @ocepaf!

One thing I don't understand is why it worked a month ago with the same recipe...

We were able to fix it by building with MKL for Windows 👍

**Comment by ocefpaf** [comment]
@basnijholt I believe that even without an `openblas` build of `scipy` this was fixed with @isuruf's brilliant "blas-split" that we rolled a few motnhs ago. Closing this but feel free to re-open if that does not fix your problem.
